spring:
  profiles:
    active: test
    

---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: springcloud-provider
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
---
server:
  port: 7002
spring:
  profiles: test
  application:
    name: springcloud-provider
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/