spring:
  proflies:
    active: dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.demo.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  proflies: dev
  application:
    name: springcloud-config-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-8001
info:
  app.name: taosun-microservicecloud
  company.name: www.taosun.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}




---
server:
  port: 8002
mybatis:
  type-aliases-package: com.demo.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  proflies: test
  application:
    name: springcloud-config-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring02?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: provider-8002
info:
  app.name: taosun-microservicecloud
  company.name: www.taosun.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}





